# Generated by Django 4.0.3 on 2022-04-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=40)),
                ('dni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('posicion', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='selecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=30)),
                ('continente', models.CharField(max_length=20)),
            ],
        ),
    ]
